name: PvPFriend
author: LilCrispy2o9/Angelo Vidrio
description: A Plugin To Manage FoE
version: 0.0.1
main: PvPFriend\Main
api: [1.11.0]
depends: PurePerms
commands:
  friend:
    description: use /friend help for all parameters
    permission: friend.command
  unfriend:
    description: use /friend help for all parameters
    permission: unfriend.command
permissions:
  friend.command:
    default: true
    description: "Allow use of all friend commands"
  unfriend.command:
    default: true
    description: "Allow use of all friend commands"
