name: PvPFriend
author: Crispy
description: A Plugin For Easily Managing Mods
version: 0.0.1
main: PvPFriend\Main
api: [1.4.0]
commands:
  pf:
    description: use /f help for all parameters
    permission: cl.command
permissions:
  pf.command:
    default: true
    description: "Allow use of all faction commands"
