name: iFriend
author: LilCrispy2o9/Angelo Vidrio
description: A Plugin To Manage FoE
version: 1.0.2
main: iFriend\Main
api: [1.10.0]
commands:
  friend:
    description: Use /friend help for all parameters
    permission: friend.command
  unfriend:
    description: Use /friend help for all parameters
    permission: unfriend.command
permissions:
  friend.command:
    default: true
    description: "Allow use of all friend commands"
  unfriend.command:
    default: true
    description: "Allow use of all friend commands"
