name: PvPFriend
author: Crispy
description: A Plugin To Manage FoE
version: 0.0.1
main: PvPFriend\Main
api: [1.4.0]
commands:
  pf:
    description: use /pf help for all parameters
    permission: pf.command
permissions:
  pf.command:
    default: true
    description: "Allow use of all friend commands"
